#:schema node_modules/wrangler/config-schema.json
name = "subapi-xiaoyetech"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "7f9ad0e142914eabafaf5de8ef8857d1" }
]
